### ISSUE TITLE
Multiples SIGSEGV a day

### ISSUE THREAD

**Issue by rphlrmblt** [syepes/network_exporter#30]
I never had this kind of problem with the 1.6.2 version, but since I've upgraded to 1.6.4, I've sometimes 2 ou 3 time a day this kind of crash : 

```log
janv. 10 12:25:15 server network_exporter[1090]: panic: runtime error: invalid memory address or nil pointer dereference
janv. 10 12:25:15 server network_exporter[1090]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8ba4e1]
janv. 10 12:25:15 server network_exporter[1090]: goroutine 62333 [running]:
janv. 10 12:25:15 server network_exporter[1090]: github.com/syepes/network_exporter/pkg/tcp.Port({0xc00022e080, 0x7}, {0xc0001209c7, 0x7}, {0x0, 0x0}, {0xc00022e088, 0x3}, 0x6fc23ac00, 0x3b9aca00)
janv. 10 12:25:15 server network_exporter[1090]:         /home/runner/work/network_exporter/network_exporter/pkg/tcp/tcp.go:45 +0x441
janv. 10 12:25:15 server network_exporter[1090]: github.com/syepes/network_exporter/target.(*TCPPort).portCheck(0xc00013e6e0)
janv. 10 12:25:15 server network_exporter[1090]:         /home/runner/work/network_exporter/network_exporter/target/target_tcp.go:81 +0x65
janv. 10 12:25:15 server network_exporter[1090]: created by github.com/syepes/network_exporter/target.(*TCPPort).run
janv. 10 12:25:15 server network_exporter[1090]:         /home/runner/work/network_exporter/network_exporter/target/target_tcp.go:69 +0xa7
```

It's hard to reproduce it, I didn't find a special thing that trigger it.

**Comment by syepes** [comment]
Thanks for reporting this, I'll give it a look

**Comment by rphlrmblt** [comment]
Installed the 1.6.5 this norming, I'll see in a couple of days if no more SIGSEGV. Thanks you.
